### ISSUE TITLE
Practica5 ProcesodeNegocio

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipowar#1]
https://drive.google.com/file/d/1FmygkVLptTMPyBZTYaYqWO71i10s5F7H/view?usp=sharing

**Comment by 22620229Angel** [comment]
en lo que hemos revisado le otrogamos una calificacion de 20/20 ya que cumple con lo necesario

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
